
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ru';
  setLanguage: (lang: 'en' | 'ru') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero Section
    appName: "Return Yourself",
    slogan: "Your mental well-being is our priority",
    startNow: "Start Now",
    supportMessage: "Remember: you are not alone. Help is always available.",
    
    hello: "Hello",
    welcome: "Welcome",
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    heroTitle: "Your Mental Well-being is Our Priority",
    heroSubtitle: "Discover resources and support to help you thrive.",
    getStarted: "Get Started",
    copyright: "© 2024 Mental Health App. All rights reserved.",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    howCanWeHelp: "How can we help you today?",
    chooseWhatFeels: "Choose what feels right for you",
    bookSession: "Book a Session",
    bookSessionDesc: "Schedule a consultation with a specialist",
    emotionalCheckup: "Emotional Check-up",
    emotionalCheckupDesc: "Quick assessment of your emotional state",
    readListen: "Read & Listen",
    readListenDesc: "Helpful articles and audio content",
    sosTools: "SOS Tools",
    sosToolsDesc: "Immediate help when you're overwhelmed",
    emergencyContact: "Emergency Contact",
    emergencyContactDesc: "Quick access to crisis support",
    yourProgress: "Your Progress",
    yourProgressDesc: "Track your journey and achievements",
    urgent: "URGENT",
    userName: "User Name",
    userEmail: "user@example.com",
    settings: "Settings",
    logout: "Logout",
    backToMenu: "Back to Menu",
    howAreYouSleeping: "How are you sleeping lately?",
    sleepingWell: "I'm sleeping well",
    someDifficulty: "Some difficulty falling asleep",
    veryPoorly: "Very poorly, constant insomnia",
    howOftenThinkAboutHer: "How often do you think about her?",
    rarely: "Rarely",
    sometimes: "Sometimes",
    constantly: "Constantly",
    howIsEnergyLevel: "How is your energy level?",
    goodEnergy: "Good energy",
    lowEnergy: "Low energy",
    exhausted: "Completely exhausted",
    takingCareOfYourself: "Are you taking care of yourself?",
    yesRegularly: "Yes, regularly",
    notReally: "Not really",
    howFeelAboutFuture: "How do you feel about the future?",
    hopeful: "Hopeful",
    uncertain: "Uncertain",
    hopeless: "Hopeless",
    managingWell: "You're managing well!",
    managingWellMessage: "You show good emotional resilience. Keep taking care of yourself.",
    workingThrough: "You're working through it",
    workingThroughMessage: "You're experiencing some challenges but showing strength in coping.",
    struggling: "You're struggling right now",
    strugglingMessage: "It's okay to not be okay. Professional support can really help.",
    tryTechnique: "Try SOS Techniques",
    bookingFeature: "Booking feature coming soon!",
    greatProgress: "Great progress!",
    sosToolsTitle: "SOS Tools",
    quickReliefOverwhelmed: "Quick relief when you're overwhelmed",
    breathingExercise478: "4-7-8 Breathing Exercise",
    breathingExerciseDesc: "Calming breathing technique for anxiety relief",
    startBreathing: "Start Breathing",
    grounding5432: "5-4-3-2-1 Grounding",
    groundingDesc: "Mindfulness technique to return to the present moment",
    beginGrounding: "Begin Grounding",
    thoughtRelease: "Thought Release",
    thoughtReleaseDesc: "Write down your thoughts to clear your mind",
    startWriting: "Start Writing",
    quickMovement: "Quick Movement",
    quickMovementDesc: "Simple exercises to release stress",
    getMoving: "Get Moving",
    stopExercise: "Stop Exercise",
    breatheIn: "Breathe In",
    hold: "Hold",
    breatheOut: "Breathe Out",
    fillLungsSlowly: "Fill your lungs slowly with air",
    holdBreathCalm: "Hold your breath, stay calm",
    releaseAllTension: "Release all tension",
    imFeelingBetter: "I'm feeling better",
    backToTools: "Back to Tools",
    groundingExerciseTitle: "5-4-3-2-1 Grounding Exercise",
    groundingStep1: "5 things you can SEE around you",
    groundingStep2: "4 things you can TOUCH",
    groundingStep3: "3 sounds you can HEAR",
    groundingStep4: "2 scents you can SMELL",
    groundingStep5: "1 taste in your mouth",
    imMoreGrounded: "I feel more grounded",
    crisisHelplineWarning: "If you feel you are in crisis, please contact the crisis helpline immediately: 8-800-2000-122",
    emergencyContactTitle: "Emergency Contact",
    whenYouNeedHelp: "When you need immediate help",
    crisisHotline: "Crisis Hotline",
    crisisHotlineDesc: "24/7 support for crisis situations",
    callNow: "Call Now",
    textSupport: "Text Support",
    textSupportDesc: "Anonymous help via text messages",
    startChat: "Start Chat",
    onlineSupport: "Online Support",
    onlineSupportDesc: "Instant help through the internet",
    getHelp: "Get Help",
    localResources: "Local Resources",
    localResourcesDesc: "Find help in your area",
    findResources: "Find Resources",
    rememberNotAlone: "Remember: you are not alone. Help is always available.",
    yourProgressTitle: "Your Progress",
    trackingYourJourney: "Tracking your journey to well-being",
    emotionalWellbeing: "Emotional Well-being",
    thisWeek: "This Week",
    checkupsCompleted: "Check-ups Completed",
    averageScore: "Average Score",
    sessionsBooked: "Sessions Booked",
    recentActivity: "Recent Activity",
    completedCheckup: "Completed emotional check-up",
    usedSOSTools: "Used SOS tools",
    readArticle: "Read article",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo2: "2 days ago",
    achievements: "Achievements",
    firstCheckup: "First Check-up",
    weekStreak: "Week Streak",
    sosExpert: "SOS Expert",
    completedFirst: "Completed your first emotional check-up",
    activeForWeek: "Active for a week straight",
    used5SOSTools: "Used 5 different SOS tools",
    viewDetailedReport: "View Detailed Report",
    helpfulContent: "Helpful content for your well-being",
    wantMoreContent: "Want more personalized content?",
    personalizedResources: "Get resources tailored to your needs",
    requestSession: "Request a Session",
    savedToReading: "Saved to your reading list",
    describeRequest: "Describe your request",
    feelingOverwhelmedPlaceholder: "I'm feeling overwhelmed and need support with...",
    chooseFormat: "Choose format",
    online: "Online",
    inPerson: "In Person",
    selectDate: "Select date",
    selectTime: "Select time",
    pleaseSelect: "Please fill in all fields",
    sessionBooked: "Session successfully booked!",
    bookSessionBtn: "Book Session",
    cancel: "Cancel",
    confirm: "Confirm"
  },
  ru: {
    // Hero Section
    appName: "Вернись к Себе",
    slogan: "Ваше психическое благополучие - наш приоритет",
    startNow: "Начать сейчас",
    supportMessage: "Помните: вы не одни. Помощь всегда доступна.",
    
    hello: "Привет",
    welcome: "Добро пожаловать",
     home: "Главная",
     about: "О нас",
     services: "Услуги",
     contact: "Контакт",
     heroTitle: "Ваше психическое здоровье - наш приоритет",
     heroSubtitle: "Откройте для себя ресурсы и поддержку, которые помогут вам процветать.",
     getStarted: "Начать",
     copyright: "© 2024 Mental Health App. Все права защищены.",
     termsOfService: "Условия использования",
     privacyPolicy: "Политика конфиденциальности",
    howCanWeHelp: "Как мы можем помочь вам сегодня?",
    chooseWhatFeels: "Выберите то, что подходит именно вам",
    bookSession: "Записаться на сессию",
    bookSessionDesc: "Запланировать консультацию со специалистом",
    emotionalCheckup: "Эмоциональная диагностика",
    emotionalCheckupDesc: "Быстрая оценка вашего эмоционального состояния",
    readListen: "Читать и слушать",
    readListenDesc: "Полезные статьи и аудиоконтент",
    sosTools: "SOS Инструменты",
    sosToolsDesc: "Немедленная помощь в трудные моменты",
    emergencyContact: "Экстренная связь",
    emergencyContactDesc: "Быстрый доступ к кризисной поддержке",
    yourProgress: "Твой прогресс",
    yourProgressDesc: "Отслеживай свой путь и достижения",
    urgent: "СРОЧНО",
    userName: "Имя пользователя",
    userEmail: "user@example.com",
    settings: "Настройки",
    logout: "Выйти",
    backToMenu: "Назад в меню",
    howAreYouSleeping: "Как дела со сном в последнее время?",
    sleepingWell: "Сплю хорошо, высыпаюсь",
    someDifficulty: "Иногда сложно заснуть",
    veryPoorly: "Очень плохо, мучает бессонница",
    howOftenThinkAboutHer: "Как часто вы думаете о прошлых отношениях?",
    rarely: "Редко вспоминаю",
    sometimes: "Иногда думаю об этом",
    constantly: "Думаю об этом постоянно",
    howIsEnergyLevel: "Как ваш уровень энергии?",
    goodEnergy: "Полон сил и энергии",
    lowEnergy: "Чувствую упадок сил",
    exhausted: "Полностью истощен",
    takingCareOfYourself: "Заботитесь ли вы о себе в последнее время?",
    yesRegularly: "Да, регулярно слежу за собой",
    notReally: "Не особо забочусь о себе",
    howFeelAboutFuture: "Как вы смотрите на будущее?",
    hopeful: "С надеждой и оптимизмом",
    uncertain: "Неуверенно, все туманно",
    hopeless: "Безнадежно, не вижу перспектив",
    managingWell: "Вы отлично справляетесь!",
    managingWellMessage: "Ваше эмоциональное состояние стабильное. Вы проявляете хорошую устойчивость к стрессу и умеете заботиться о себе. Продолжайте в том же духе!",
    workingThrough: "Вы работаете над собой",
    workingThroughMessage: "Сейчас вы переживаете некоторые трудности, но показываете силу духа в их преодолении. Это нормальный процесс восстановления.",
    struggling: "Вам сейчас очень тяжело",
    strugglingMessage: "Вы переживаете серьезные эмоциональные трудности. Помните - это временно, и профессиональная поддержка может значительно облегчить ваше состояние.",
    tryTechnique: "Попробовать SOS техники",
    bookingFeature: "Функция записи скоро появится!",
    greatProgress: "Отличный прогресс!",
    sosToolsTitle: "SOS Инструменты",
    quickReliefOverwhelmed: "Быстрая помощь когда тяжело",
    breathingExercise478: "Дыхательное упражнение 4-7-8",
    breathingExerciseDesc: "Успокаивающая техника дыхания для снятия тревоги",
    startBreathing: "Начать дыхание",
    grounding5432: "Заземление 5-4-3-2-1",
    groundingDesc: "Техника осознанности для возвращения в настоящий момент",
    beginGrounding: "Начать заземление",
    thoughtRelease: "Освобождение мыслей",
    thoughtReleaseDesc: "Запишите свои мысли, чтобы освободить разум",
    startWriting: "Начать писать",
    quickMovement: "Быстрое движение",
    quickMovementDesc: "Простые упражнения для сброса стресса",
    getMoving: "Начать движение",
    stopExercise: "Остановить упражнение",
    breatheIn: "Вдох",
    hold: "Задержите",
    breatheOut: "Выдох",
    fillLungsSlowly: "Медленно наполните легкие воздухом",
    holdBreathCalm: "Задержите дыхание, оставайтесь спокойными",
    releaseAllTension: "Выпустите все напряжение",
    imFeelingBetter: "Мне стало лучше",
    backToTools: "Назад к инструментам",
    groundingExerciseTitle: "Упражнение заземления 5-4-3-2-1",
    groundingStep1: "5 вещей, которые вы ВИДИТЕ вокруг себя",
    groundingStep2: "4 вещи, которые вы можете ПОТРОГАТЬ",
    groundingStep3: "3 звука, которые вы СЛЫШИТЕ",
    groundingStep4: "2 запаха, которые вы ЧУВСТВУЕТЕ",
    groundingStep5: "1 вкус во рту",
    imMoreGrounded: "Я чувствую себя более заземленным",
    crisisHelplineWarning: "Если вы чувствуете, что находитесь в кризисе, немедленно обратитесь на горячую линию помощи: 8-800-2000-122",
    emergencyContactTitle: "Экстренная связь",
    whenYouNeedHelp: "Когда нужна немедленная помощь",
    crisisHotline: "Кризисная горячая линия",
    crisisHotlineDesc: "Круглосуточная поддержка в кризисных ситуациях",
    callNow: "Позвонить сейчас",
    textSupport: "Поддержка через SMS",
    textSupportDesc: "Анонимная помощь через текстовые сообщения",
    startChat: "Начать чат",
    onlineSupport: "Онлайн поддержка",
    onlineSupportDesc: "Мгновенная помощь через интернет",
    getHelp: "Получить помощь",
    localResources: "Местные ресурсы",
    localResourcesDesc: "Найти помощь в вашем регионе",
    findResources: "Найти ресурсы",
    rememberNotAlone: "Помните: вы не одни. Помощь всегда доступна.",
    yourProgressTitle: "Твой прогресс",
    everyStepForwardMatters: "Каждый шаг вперед имеет значение",
    daysOfProgress: "дней прогресса",
    achievements: "достижений",
    addProgress: "Добавить прогресс",
    whatProgressMade: "Какой прогресс вы сделали?",
    progressPlaceholder: "Например: сегодня пошел на прогулку, поговорил с другом...",
    addProgressBtn: "Добавить прогресс",
    cancel: "Отмена",
    yourJourney: "Ваш путь",
    didntCheckSocialMedia: "Не проверял социальные сети весь день",
    wentToGym: "Сходил в спортзал",
    hadDinnerWithFriends: "Поужинал с друзьями",
    completedEmotionalCheckup: "Прошел эмоциональную диагностику",
    startedUsingApp: "Начал пользоваться приложением",
    today: "Сегодня",
    yesterday: "Вчера",
    twoDaysAgo: "2 дня назад",
    threeDaysAgo: "3 дня назад",
    oneWeekAgo: "Неделю назад",
    youMakingProgress: "Вы делаете успехи!",
    recoveryNotLinear: "Восстановление - это не прямая линия. Гордитесь каждым маленьким шагом вперед.",
    pleaseDescribeYourProgress: "Пожалуйста, опишите ваш прогресс",
    progressAddedGreat: "Прогресс добавлен! Отлично!",
    trackingYourJourney: "Отслеживание вашего пути к благополучию",
    emotionalWellbeing: "Эмоциональное благополучие",
    thisWeek: "На этой неделе",
    checkupsCompleted: "Диагностик завершено",
    averageScore: "Средний балл",
    sessionsBooked: "Сессий забронировано",
    recentActivity: "Недавняя активность",
    completedCheckup: "Завершена эмоциональная диагностика",
    usedSOSTools: "Использованы SOS инструменты",
    readArticle: "Прочитана статья",
    daysAgo2: "2 дня назад",
    firstCheckup: "Первая диагностика",
    weekStreak: "Неделя активности",
    sosExpert: "Эксперт SOS",
    completedFirst: "Завершили первую эмоциональную диагностику",
    activeForWeek: "Активны в течение недели подряд",
    used5SOSTools: "Использовали 5 различных SOS инструментов",
    viewDetailedReport: "Посмотреть подробный отчет",
    helpfulContent: "Полезный контент для вашего благополучия",
    wantMoreContent: "Хотите больше персонализированного контента?",
    personalizedResources: "Получите ресурсы, адаптированные под ваши потребности",
    requestSession: "Запросить сессию",
    savedToReading: "Сохранено в список для чтения",
    describeRequest: "Опишите ваш запрос",
    feelingOverwhelmedPlaceholder: "Я чувствую себя подавленным и нуждаюсь в поддержке с...",
    chooseFormat: "Выберите формат",
    online: "Онлайн",
    inPerson: "Лично",
    selectDate: "Выберите дату",
    selectTime: "Выберите время",
    pleaseSelect: "Пожалуйста, заполните все поля",
    sessionBooked: "Сессия успешно забронирована!",
    bookSessionBtn: "Забронировать сессию",
    confirm: "Подтвердить"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'ru'>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
