import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ru';
  setLanguage: (lang: 'en' | 'ru') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero Section
    appName: "Return Yourself",
    slogan: "Your mental well-being is our priority",
    startNow: "Start Now",
    supportMessage: "Remember: you are not alone. Help is always available.",
    
    hello: "Hello",
    welcome: "Welcome",
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    heroTitle: "Your Mental Well-being is Our Priority",
    heroSubtitle: "Discover resources and support to help you thrive.",
    getStarted: "Get Started",
    copyright: "© 2024 Mental Health App. All rights reserved.",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    howCanWeHelp: "How can we help you today?",
    chooseWhatFeels: "Choose what feels right for you",
    bookSession: "Book a Session",
    bookSessionDesc: "Schedule a consultation with a specialist",
    emotionalCheckup: "Emotional Check-up",
    emotionalCheckupDesc: "Quick assessment of your emotional state",
    readListen: "Read & Listen",
    readListenDesc: "Helpful articles and audio content",
    sosTools: "SOS Tools",
    sosToolsDesc: "Immediate help when you're overwhelmed",
    emergencyContact: "Emergency Contact",
    emergencyContactDesc: "Quick access to crisis support",
    yourProgress: "Your Progress",
    yourProgressDesc: "Track your journey and achievements",
    urgent: "URGENT",
    userName: "User Name",
    userEmail: "user@example.com",
    settings: "Settings",
    logout: "Logout",
    backToMenu: "Back to Menu",
    howAreYouSleeping: "How are you sleeping lately?",
    sleepingWell: "I'm sleeping well",
    someDifficulty: "Some difficulty falling asleep",
    veryPoorly: "Very poorly, constant insomnia",
    howOftenThinkAboutHer: "How often do you think about her?",
    rarely: "Rarely",
    sometimes: "Sometimes",
    constantly: "Constantly",
    howIsEnergyLevel: "How is your energy level?",
    goodEnergy: "Good energy",
    lowEnergy: "Low energy",
    exhausted: "Completely exhausted",
    takingCareOfYourself: "Are you taking care of yourself?",
    yesRegularly: "Yes, regularly",
    notReally: "Not really",
    howFeelAboutFuture: "How do you feel about the future?",
    hopeful: "Hopeful",
    uncertain: "Uncertain",
    hopeless: "Hopeless",
    managingWell: "You're managing well!",
    managingWellMessage: "You show good emotional resilience. Keep taking care of yourself.",
    workingThrough: "You're working through it",
    workingThroughMessage: "You're experiencing some challenges but showing strength in coping.",
    struggling: "You're struggling right now",
    strugglingMessage: "It's okay to not be okay. Professional support can really help.",
    tryTechnique: "Try SOS Techniques",
    bookingFeature: "Booking feature coming soon!",
    greatProgress: "Great progress!",
    sosToolsTitle: "SOS Tools",
    quickReliefOverwhelmed: "Quick relief when you're overwhelmed",
    breathingExercise478: "4-7-8 Breathing Exercise",
    breathingExerciseDesc: "Calming breathing technique for anxiety relief",
    startBreathing: "Start Breathing",
    grounding5432: "5-4-3-2-1 Grounding",
    groundingDesc: "Mindfulness technique to return to the present moment",
    beginGrounding: "Begin Grounding",
    thoughtRelease: "Thought Release",
    thoughtReleaseDesc: "Write down your thoughts to clear your mind",
    startWriting: "Start Writing",
    quickMovement: "Quick Movement",
    quickMovementDesc: "Simple exercises to release stress",
    getMoving: "Get Moving",
    stopExercise: "Stop Exercise",
    breatheIn: "Breathe In",
    hold: "Hold",
    breatheOut: "Breathe Out",
    fillLungsSlowly: "Fill your lungs slowly with air",
    holdBreathCalm: "Hold your breath, stay calm",
    releaseAllTension: "Release all tension",
    imFeelingBetter: "I'm feeling better",
    backToTools: "Back to Tools",
    groundingExerciseTitle: "5-4-3-2-1 Grounding Exercise",
    groundingStep1: "5 things you can SEE around you",
    groundingStep2: "4 things you can TOUCH",
    groundingStep3: "3 sounds you can HEAR",
    groundingStep4: "2 scents you can SMELL",
    groundingStep5: "1 taste in your mouth",
    imMoreGrounded: "I feel more grounded",
    crisisHelplineWarning: "If you feel you are in crisis, please contact the crisis helpline immediately: 8-800-2000-122",
    emergencyContactTitle: "Emergency Contact",
    whenYouNeedHelp: "When you need immediate help",
    crisisHotline: "Crisis Hotline",
    crisisHotlineDesc: "24/7 support for crisis situations",
    callNow: "Call Now",
    textSupport: "Text Support",
    textSupportDesc: "Anonymous help via text messages",
    startChat: "Start Chat",
    onlineSupport: "Online Support",
    onlineSupportDesc: "Instant help through the internet",
    getHelp: "Get Help",
    localResources: "Local Resources",
    localResourcesDesc: "Find help in your area",
    findResources: "Find Resources",
    rememberNotAlone: "Remember: you are not alone. Help is always available.",
    yourProgressTitle: "Your Progress",
    trackingYourJourney: "Tracking your journey to well-being",
    emotionalWellbeing: "Emotional Well-being",
    thisWeek: "This Week",
    checkupsCompleted: "Check-ups Completed",
    averageScore: "Average Score",
    sessionsBooked: "Sessions Booked",
    recentActivity: "Recent Activity",
    completedCheckup: "Completed emotional check-up",
    usedSOSTools: "Used SOS tools",
    readArticle: "Read article",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo2: "2 days ago",
    achievements: "Achievements",
    firstCheckup: "First Check-up",
    weekStreak: "Week Streak",
    sosExpert: "SOS Expert",
    completedFirst: "Completed your first emotional check-up",
    activeForWeek: "Active for a week straight",
    used5SOSTools: "Used 5 different SOS tools",
    viewDetailedReport: "View Detailed Report",
    helpfulContent: "Helpful content for your well-being",
    wantMoreContent: "Want more personalized content?",
    personalizedResources: "Get resources tailored to your needs",
    requestSession: "Request a Session",
    savedToReading: "Saved to your reading list",
    describeRequest: "Describe your request",
    feelingOverwhelmedPlaceholder: "I'm feeling overwhelmed and need support with...",
    chooseFormat: "Choose format",
    online: "Online",
    inPerson: "In Person",
    selectDate: "Select date",
    selectTime: "Select time",
    pleaseSelect: "Please fill in all fields",
    sessionBooked: "Session successfully booked!",
    bookSessionBtn: "Book Session",
    cancel: "Cancel",
    confirm: "Confirm",
    
    // New translations for movement exercise
    movementInstructions: "Follow these simple movements to release stress and tension",
    step: "Step",
    of: "of",
    previous: "Previous",
    next: "Next",
    complete: "Complete",
    movementStep1: "Take 5 deep breaths while stretching your arms up",
    movementStep2: "Roll your shoulders back 10 times",
    movementStep3: "Gently turn your head left and right 5 times each",
    movementStep4: "Shake your hands and feet for 30 seconds",
    movementStep5: "Take 3 more deep breaths and smile",
    
    // New translations for thought release
    writeDownThoughts: "Write down your thoughts to help process and release them",
    thoughtPlaceholder: "What's on your mind? Write freely without judgment...",
    writingPrivate: "Your writing is completely private and will not be saved",
    clearText: "Clear Text",
    feelingBetter: "I'm Feeling Better"
  },
  ru: {
    // Hero Section
    appName: "Вернись к Себе",
    slogan: "Ваше психическое благополучие - наш приоритет",
    startNow: "Начать сейчас",
    supportMessage: "Помните: вы не одни. Помощь всегда доступна.",
    
    hello: "Привет",
    welcome: "Добро пожаловать",
     home: "Главная",
     about: "О нас",
     services: "Услуги",
     contact: "Контакт",
     heroTitle: "Ваше психическое здоровье - наш приоритет",
     heroSubtitle: "Откройте для себя ресурсы и поддержку, которые помогут вам процветать.",
     getStarted: "Начать",
     copyright: "© 2024 Mental Health App. Все права защищены.",
     termsOfService: "Условия использования",
     privacyPolicy: "Политика конфиденциальности",
    howCanWeHelp: "Как мы можем помочь вам сегодня?",
    chooseWhatFeels: "Выберите то, что подходит именно вам",
    bookSession: "Записаться на сессию",
    bookSessionDesc: "Запланировать консультацию со специалистом",
    emotionalCheckup: "Эмоциональная диагностика",
    emotionalCheckupDesc: "Быстро узнайте свое эмоциональное состояние",
    readListen: "Читать и слушать",
    readListenDesc: "Полезные статьи и аудиоконтент для поддержки",
    sosTools: "SOS Инструменты",
    sosToolsDesc: "Мгновенная помощь когда становится тяжело",
    emergencyContact: "Экстренная связь",
    emergencyContactDesc: "Круглосуточная поддержка в кризисных ситуациях",
    yourProgress: "Твой прогресс",
    yourProgressDesc: "Отслеживай свой путь восстановления",
    urgent: "СРОЧНО",
    userName: "Имя пользователя",
    userEmail: "user@example.com",
    settings: "Настройки",
    logout: "Выйти",
    backToMenu: "Назад в меню",
    
    // Emotional Checkup - New Questions
    howAreYouToday: "Как вы себя чувствуете сегодня?",
    feelGreat: "Отлично, полон энергии",
    feelGood: "Хорошо, настроение стабильное",
    feelOkay: "Нормально, но есть тревога",
    feelBad: "Плохо, грустно и тяжело",
    feelTerrible: "Ужасно, не могу справиться",
    
    howIsYourSleep: "Как дела со сном?",
    sleepWell: "Сплю крепко, высыпаюсь",
    sleepOkay: "В целом нормально",
    sleepPoor: "Часто просыпаюсь ночью",
    sleepBad: "Мучает бессонница",
    
    stressLevel: "Уровень стресса сегодня?",
    noStress: "Спокоен и расслаблен",
    lightStress: "Легкое напряжение",
    moderateStress: "Заметный стресс",
    highStress: "Сильное напряжение",
    extremeStress: "Критический уровень",
    
    socialConnections: "Общение с близкими?",
    goodConnections: "Активно общаюсь",
    someConnections: "Иногда встречаюсь",
    limitedConnections: "Редко вижусь",
    noConnections: "Избегаю общения",
    
    copingAbility: "Справляетесь с трудностями?",
    copingWell: "Легко нахожу решения",
    copingOkay: "Справляюсь с усилием",
    copingPoor: "Часто теряюсь",
    notCoping: "Не могу справиться",
    
    // Results
    excellentState: "Отличное состояние!",
    excellentMessage: "Вы находитесь в прекрасной эмоциональной форме. У вас стабильное настроение, хороший сон и высокая стрессоустойчивость.",
    excellentSuggestion: "Продолжайте поддерживать здоровые привычки и делитесь своим опытом с другими.",
    
    goodState: "Хорошее состояние",
    goodMessage: "В целом вы справляетесь хорошо, но есть области для улучшения. Ваше эмоциональное состояние стабильное.",
    goodSuggestion: "Обратите внимание на режим сна и управление стрессом. Регулярные техники релаксации помогут.",
    
    moderateState: "Умеренные трудности",
    moderateMessage: "Вы переживаете определенные эмоциональные трудности, но показываете силу в их преодолении.",
    moderateSuggestion: "Рекомендуем попробовать техники самопомощи и подумать о консультации специалиста.",
    
    difficultState: "Сложный период",
    difficultMessage: "Сейчас вам довольно тяжело. Вы испытываете серьезные эмоциональные трудности, которые влияют на повседневную жизнь.",
    difficultSuggestion: "Важно обратиться за профессиональной помощью. Вы не одни, и поддержка доступна.",
    
    criticalState: "Критическое состояние",
    criticalMessage: "Вы переживаете очень тяжелый период. Ваше эмоциональное состояние требует немедленного внимания.",
    criticalSuggestion: "Настоятельно рекомендуем немедленно обратиться к специалисту. Есть экстренные службы поддержки.",
    
    // Emergency Contact - Updated translations
    emergencyContactTitle: "Экстренная связь",
    needImmediateHelp: "Когда нужна немедленная помощь",
    hereToHelpYou: "Мы здесь, чтобы поддержать вас в трудную минуту",
    crisisWarningMessage: "Если вы находитесь в кризисной ситуации или думаете о причинении вреда себе, немедленно обратитесь за помощью: 112 или 8-800-2000-122",
    tellUsWhatsHappening: "Расскажите, что происходит",
    feelingOverwhelmedBecause: "Мне тяжело, потому что...",
    howToContactYou: "Как с вами связаться?",
    telegram: "Телеграм",
    phone: "Телефон",
    email: "Электронная почта",
    whenNeedResponse: "Когда нужен ответ?",
    within1Hour: "В течение часа",
    within4Hours: "В течение 4 часов",
    within12Hours: "В течение 12 часов",
    sendRequest: "Отправить запрос",
    pleaseDescribeWhatsHappening: "Пожалуйста, опишите что происходит",
    weGotYourMessage: "Мы получили ваше сообщение",
    youreNotAlone: "Вы не одни. Мы свяжемся с вами в течение",
    inTheMeantime: "А пока попробуйте техники быстрой помощи из раздела SOS или обратитесь к близким людям.",
    yourMessageSent: "Ваше сообщение отправлено",
    
    bookingFeature: "Функция записи скоро появится!",
    greatProgress: "Отличный прогресс!",
    sosToolsTitle: "SOS Инструменты",
    quickReliefOverwhelmed: "Быстрая помощь когда тяжело",
    breathingExercise478: "Дыхательное упражнение 4-7-8",
    breathingExerciseDesc: "Успокаивающая техника дыхания для снятия тревоги",
    startBreathing: "Начать дыхание",
    grounding5432: "Заземление 5-4-3-2-1",
    groundingDesc: "Техника осознанности для возвращения в настоящий момент",
    beginGrounding: "Начать заземление",
    thoughtRelease: "Освобождение мыслей",
    thoughtReleaseDesc: "Запишите свои мысли, чтобы освободить разум",
    startWriting: "Начать писать",
    quickMovement: "Быстрое движение",
    quickMovementDesc: "Простые упражнения для сброса стресса",
    getMoving: "Начать движение",
    stopExercise: "Остановить упражнение",
    breatheIn: "Вдох",
    hold: "Задержите",
    breatheOut: "Выдох",
    fillLungsSlowly: "Медленно наполните легкие воздухом",
    holdBreathCalm: "Задержите дыхание, оставайтесь спокойными",
    releaseAllTension: "Выпустите все напряжение",
    imFeelingBetter: "Мне стало лучше",
    backToTools: "Назад к инструментам",
    groundingExerciseTitle: "Упражнение заземления 5-4-3-2-1",
    groundingStep1: "5 вещей, которые вы ВИДИТЕ вокруг себя",
    groundingStep2: "4 вещи, которые вы можете ПОТРОГАТЬ",
    groundingStep3: "3 звука, которые вы СЛЫШИТЕ",
    groundingStep4: "2 запаха, которые вы ЧУВСТВУЕТЕ",
    groundingStep5: "1 вкус во рту",
    imMoreGrounded: "Я чувствую себя более заземленным",
    crisisHelplineWarning: "Если вы чувствуете, что находитесь в кризисе, немедленно обратитесь на горячую линию помощи: 8-800-2000-122",
    whenYouNeedHelp: "Когда нужна немедленная помощь",
    crisisHotline: "Кризисная горячая линия",
    crisisHotlineDesc: "Круглосуточная поддержка в кризисных ситуациях",
    callNow: "Позвонить сейчас",
    textSupport: "Поддержка через SMS",
    textSupportDesc: "Анонимная помощь через текстовые сообщения",
    startChat: "Начать чат",
    onlineSupport: "Онлайн поддержка",
    onlineSupportDesc: "Мгновенная помощь через интернет",
    getHelp: "Получить помощь",
    localResources: "Местные ресурсы",
    localResourcesDesc: "Найти помощь в вашем регионе",
    findResources: "Найти ресурсы",
    rememberNotAlone: "Помните: вы не одни. Помощь всегда доступна.",
    yourProgressTitle: "Твой прогресс",
    everyStepForwardMatters: "Каждый шаг вперед имеет значение",
    daysOfProgress: "дней прогресса",
    achievements: "достижений",
    addProgress: "Добавить прогресс",
    whatProgressMade: "Какой прогресс вы сделали?",
    progressPlaceholder: "Например: сегодня пошел на прогулку, поговорил с другом...",
    addProgressBtn: "Добавить прогресс",
    cancel: "Отмена",
    yourJourney: "Ваш путь",
    didntCheckSocialMedia: "Не проверял социальные сети весь день",
    wentToGym: "Сходил в спортзал",
    hadDinnerWithFriends: "Поужинал с друзьями",
    completedEmotionalCheckup: "Прошел эмоциональную диагностику",
    startedUsingApp: "Начал пользоваться приложением",
    today: "Сегодня",
    yesterday: "Вчера",
    twoDaysAgo: "2 дня назад",
    threeDaysAgo: "3 дня назад",
    oneWeekAgo: "Неделю назад",
    youMakingProgress: "Вы делаете успехи!",
    recoveryNotLinear: "Восстановление - это не прямая линия. Гордитесь каждым маленьким шагом вперед.",
    pleaseDescribeYourProgress: "Пожалуйста, опишите ваш прогресс",
    progressAddedGreat: "Прогресс добавлен! Отлично!",
    trackingYourJourney: "Отслеживание вашего пути к благополучию",
    emotionalWellbeing: "Эмоциональное благополучие",
    thisWeek: "На этой неделе",
    checkupsCompleted: "Диагностик завершено",
    averageScore: "Средний балл",
    sessionsBooked: "Сессий забронировано",
    recentActivity: "Недавняя активность",
    completedCheckup: "Завершена эмоциональная диагностика",
    usedSOSTools: "Использованы SOS инструменты",
    readArticle: "Прочитана статья",
    daysAgo2: "2 дня назад",
    firstCheckup: "Первая диагностика",
    weekStreak: "Неделя активности",
    sosExpert: "Эксперт SOS",
    completedFirst: "Завершили первую эмоциональную диагностику",
    activeForWeek: "Активны в течение недели подряд",
    used5SOSTools: "Использовали 5 различных SOS инструментов",
    viewDetailedReport: "Посмотреть подробный отчет",
    helpfulContent: "Полезный контент для вашего благополучия",
    wantMoreContent: "Хотите больше персонализированного контента?",
    personalizedResources: "Получите ресурсы, адаптированные под ваши потребности",
    requestSession: "Запросить сессию",
    savedToReading: "Сохранено в список для чтения",
    describeRequest: "Опишите ваш запрос",
    feelingOverwhelmedPlaceholder: "Я чувствую себя подавленным и нуждаюсь в поддержке с...",
    chooseFormat: "Выберите формат",
    online: "Онлайн",
    inPerson: "Лично",
    selectDate: "Выберите дату",
    selectTime: "Выберите время",
    pleaseSelect: "Пожалуйста, заполните все поля",
    sessionBooked: "Сессия успешно забронирована!",
    bookSessionBtn: "Забронировать сессию",
    confirm: "Подтвердить",
    
    // New translations for movement exercise
    movementInstructions: "Выполните эти простые движения для снятия стресса и напряжения",
    step: "Шаг",
    of: "из",
    previous: "Назад",
    next: "Далее",
    complete: "Завершить",
    movementStep1: "Сделайте 5 глубоких вдохов, поднимая руки вверх",
    movementStep2: "Сделайте круговые движения плечами назад 10 раз",
    movementStep3: "Осторожно поверните голову влево и вправо по 5 раз",
    movementStep4: "Потрясите руками и ногами в течение 30 секунд",
    movementStep5: "Сделайте еще 3 глубоких вдоха и улыбнитесь",
    
    // New translations for thought release
    writeDownThoughts: "Запишите свои мысли, чтобы помочь их обработать и отпустить",
    thoughtPlaceholder: "О чем вы думаете? Пишите свободно, без осуждения...",
    writingPrivate: "Ваши записи полностью приватны и не будут сохранены",
    clearText: "Очистить текст",
    feelingBetter: "Мне стало лучше"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'ru'>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
