import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Hero Section
    appName: "Return Yourself",
    slogan: "Not chasing her. Reclaiming you.",
    startNow: "Start Now",
    supportMessage: "You're not alone in this journey. Take the first step toward healing.",
    
    // Main Menu
    howCanWeHelp: "How can we help?",
    chooseWhatFeels: "Choose what feels right for you now",
    bookSession: "Book a Session",
    bookSessionDesc: "Professional support when you need it",
    emotionalCheckup: "Emotional Check-Up",
    emotionalCheckupDesc: "Understanding where you are right now",
    readListen: "Read / Listen",
    readListenDesc: "Helpful content for your journey",
    sosTools: "SOS Tools",
    sosToolsDesc: "Immediate help when overwhelmed",
    emergencyContact: "Emergency Contact",
    emergencyContactDesc: "Reach out for urgent support",
    yourProgress: "Your Progress",
    yourProgressDesc: "Track your healing journey",
    urgent: "URGENT",
    language: "Language",
    
    // Book Session
    backToMenu: "Back to Menu",
    professionalSupport: "Professional support when you need it",
    firstSessionFree: "First Session Free",
    freeConsultation: "Get started with a complimentary 30-minute consultation",
    chooseFormat: "Choose Format",
    online: "Online",
    videoCall: "Video call",
    inPerson: "In-Person",
    officeVisit: "Office visit",
    selectDate: "Select Date",
    selectTime: "Select Time",
    bookSessionBtn: "Book Session",
    confirmationMessage: "You'll receive a confirmation and meeting details via Telegram",
    sessionBooked: "Session booked! You'll receive a confirmation via Telegram.",
    pleaseSelect: "Please select format, date and time",
    
    // Read Listen
    helpfulContent: "Helpful content for your healing journey",
    understanding: "Understanding",
    practice: "Practice",
    action: "Action",
    growth: "Growth",
    guidance: "Guidance",
    rest: "Rest",
    wantMoreContent: "Want More Content?",
    personalizedResources: "Get personalized resources based on your progress",
    bookingFeature: "Booking feature coming soon!",
    savedToReading: "Saved to your reading list",
    requestSession: "Request Session",
    describeRequest: "Describe your request",
    
    // Emotional Checkup
    howAreYouSleeping: "How are you sleeping?",
    sleepingWell: "Sleeping well",
    someDifficulty: "Some difficulty",
    veryPoorly: "Very poorly",
    howOftenThinkAboutHer: "How often do you think about her?",
    rarely: "Rarely",
    sometimes: "Sometimes",
    constantly: "Constantly",
    howIsEnergyLevel: "How is your energy level?",
    goodEnergy: "Good energy",
    lowEnergy: "Low energy",
    exhausted: "Exhausted",
    takingCareOfYourself: "Are you taking care of yourself?",
    yesRegularly: "Yes, regularly",
    notReally: "Not really",
    howFeelAboutFuture: "How do you feel about the future?",
    hopeful: "Hopeful",
    uncertain: "Uncertain",
    hopeless: "Hopeless",
    managingWell: "You're managing well",
    managingWellMessage: "You seem to be handling things with strength. Keep focusing on your growth.",
    workingThrough: "You're working through it",
    workingThroughMessage: "This is a challenging time, but you're taking steps forward. That takes courage.",
    struggling: "You're struggling right now",
    strugglingMessage: "This is really hard, and it's okay to not be okay. You don't have to go through this alone.",
    tryTechnique: "Try SOS Tools",
    
    // SOS Tools
    sosToolsTitle: "SOS Tools",
    sosToolsDesc: "Quick relief when you're overwhelmed",
    quickReliefOverwhelmed: "Quick relief when you're overwhelmed",
    breathingExercise478: "4-7-8 Breathing",
    breathingExerciseDesc: "Calm your nervous system with controlled breathing",
    startBreathing: "Start Breathing",
    grounding5432: "5-4-3-2-1 Grounding",
    groundingDesc: "Connect with your present moment",
    beginGrounding: "Begin Grounding",
    thoughtRelease: "Thought Release",
    thoughtReleaseDesc: "Write down what's overwhelming you",
    startWriting: "Start Writing",
    quickMovement: "Quick Movement",
    quickMovementDesc: "Release tension with simple exercises",
    getMoving: "Get Moving",
    stopExercise: "Stop Exercise",
    breatheIn: "Breathe In",
    hold: "Hold",
    breatheOut: "Breathe Out",
    fillLungsSlowly: "Fill your lungs slowly and deeply",
    holdBreathCalm: "Hold your breath, stay calm",
    releaseAllTension: "Release all the tension and stress",
    imFeelingBetter: "I'm Feeling Better",
    groundingExerciseTitle: "5-4-3-2-1 Grounding Exercise",
    groundingStep1: "Look around and name 5 things you can see",
    groundingStep2: "Notice 4 things you can touch or feel",
    groundingStep3: "Listen for 3 different sounds",
    groundingStep4: "Identify 2 things you can smell",
    groundingStep5: "Think of 1 thing you can taste",
    imMoreGrounded: "I'm More Grounded Now",
    backToTools: "Back to Tools",
    crisisHelplineWarning: "If you're having thoughts of self-harm, please reach out immediately to emergency services or crisis helplines.",
    
    // Emergency Contact
    emergencyContactTitle: "Emergency Contact",
    emergencyContactDesc: "Reach out for urgent support",
    hereToHelpYou: "We're here to help you through this",
    crisisWarningMessage: "If you're having thoughts of self-harm, please call emergency services (911) or crisis helplines immediately.",
    tellUsWhatsHappening: "Tell us what's going on",
    feelingOverwhelmedBecause: "I'm feeling overwhelmed because...",
    howToContactYou: "How should we contact you?",
    telegram: "Telegram",
    phone: "Phone",
    email: "Email",
    whenNeedResponse: "When do you need a response?",
    within1Hour: "Within 1h",
    within4Hours: "Within 4h",
    within12Hours: "Within 12h",
    sendRequest: "Send Request",
    weGotYourMessage: "We've Got Your Message",
    youreNotAlone: "You're not alone in this. Someone will reach out to you within",
    inTheMeantime: "In the meantime, try some breathing exercises or reach out to a trusted friend.",
    backToMenu: "Back to Menu",
    yourMessageSent: "Your message has been sent. Help is on the way.",
    pleaseDescribeWhatsHappening: "Please tell us what's going on",
    
    // Progress
    yourProgressTitle: "Your Progress",
    yourProgressDesc: "Track your healing journey",
    everyStepForwardMatters: "Every step forward matters",
    daysOfProgress: "Days of Progress",
    achievements: "Achievements",
    addProgress: "Add Progress",
    whatProgressMade: "What progress did you make?",
    progressPlaceholder: "I did something good for myself...",
    addProgressBtn: "Add Progress",
    cancel: "Cancel",
    yourJourney: "Your Journey",
    youMakingProgress: "You're Making Progress",
    recoveryNotLinear: "Recovery isn't linear, but every step counts. Keep going.",
    progressAddedGreat: "Progress added! Great work.",
    pleaseDescribeYourProgress: "Please describe your progress",
    
    // Sample progress items
    didntCheckSocial: "Didn't check her social media",
    wentToGym: "Went to the gym",
    dinnerWithFriends: "Had dinner with friends",
    completedCheckup: "Completed emotional check-up",
    startedApp: "Started using Return Yourself app",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo2: "2 days ago",
    daysAgo3: "3 days ago",
    weekAgo: "1 week ago",
    
    // Profile
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    userName: "User Name",
    userEmail: "user@example.com"
  },
  ru: {
    // Hero Section
    appName: "Верни Себя",
    slogan: "Не гонишься за ней. Возвращаешь себя.",
    startNow: "Начать",
    supportMessage: "Ты не один в этом пути. Сделай первый шаг к исцелению.",
    
    // Main Menu
    howCanWeHelp: "Как мы можем помочь?",
    chooseWhatFeels: "Выбери то, что сейчас подходит тебе",
    bookSession: "Записаться на сессию",
    bookSessionDesc: "Профессиональная поддержка когда нужна",
    emotionalCheckup: "Эмоциональная диагностика",
    emotionalCheckupDesc: "Понимание того, где ты сейчас находишься",
    readListen: "Читать / Слушать",
    readListenDesc: "Полезный контент для твоего пути",
    sosTools: "SOS Инструменты",
    sosToolsDesc: "Немедленная помощь при перегрузке",
    emergencyContact: "Экстренная связь",
    emergencyContactDesc: "Обратиться за срочной поддержкой",
    yourProgress: "Твой прогресс",
    yourProgressDesc: "Отслеживай свой путь исцеления",
    urgent: "СРОЧНО",
    language: "Язык",
    
    // Book Session
    backToMenu: "Назад в меню",
    professionalSupport: "Профессиональная поддержка когда нужна",
    firstSessionFree: "Первая сессия бесплатно",
    freeConsultation: "Начни с бесплатной 30-минутной консультации",
    chooseFormat: "Выбери формат",
    online: "Онлайн",
    videoCall: "Видео звонок",
    inPerson: "Очно",
    officeVisit: "Визит в офис",
    selectDate: "Выбери дату",
    selectTime: "Выбери время",
    bookSessionBtn: "Записаться",
    confirmationMessage: "Ты получишь подтверждение и детали встречи в Telegram",
    sessionBooked: "Сессия забронирована! Ты получишь подтверждение в Telegram.",
    pleaseSelect: "Пожалуйста, выбери формат, дату и время",
    
    // Read Listen
    helpfulContent: "Полезный контент для твоего пути исцеления",
    understanding: "Понимание",
    practice: "Практика",
    action: "Действие",
    growth: "Рост",
    guidance: "Руководство",
    rest: "Отдых",
    wantMoreContent: "Хочешь больше контента?",
    personalizedResources: "Получи персонализированные ресурсы на основе твоего прогресса",
    bookingFeature: "Функция записи скоро появится!",
    savedToReading: "Сохранено в список для чтения",
    requestSession: "Записаться на сессию",
    describeRequest: "Опиши свой запрос",
    
    // Emotional Checkup
    howAreYouSleeping: "Как ты спишь?",
    sleepingWell: "Сплю хорошо",
    someDifficulty: "Есть трудности",
    veryPoorly: "Очень плохо",
    howOftenThinkAboutHer: "Как часто ты думаешь о ней?",
    rarely: "Редко",
    sometimes: "Иногда",
    constantly: "Постоянно",
    howIsEnergyLevel: "Как твой уровень энергии?",
    goodEnergy: "Хорошая энергия",
    lowEnergy: "Мало энергии",
    exhausted: "Истощен",
    takingCareOfYourself: "Заботишься ли ты о себе?",
    yesRegularly: "Да, регулярно",
    notReally: "Не особо",
    howFeelAboutFuture: "Что ты чувствуешь по поводу будущего?",
    hopeful: "Надежду",
    uncertain: "Неопределенность",
    hopeless: "Безнадежность",
    managingWell: "Ты хорошо справляешься",
    managingWellMessage: "Кажется, ты справляешься с ситуацией с силой. Продолжай фокусироваться на своем росте.",
    workingThrough: "Ты прорабатываешь это",
    workingThroughMessage: "Это сложное время, но ты делаешь шаги вперед. Это требует мужества.",
    struggling: "Тебе сейчас трудно",
    strugglingMessage: "Это действительно тяжело, и это нормально - не быть в порядке. Тебе не нужно проходить через это в одиночку.",
    tryTechnique: "Попробовать SOS инструменты",
    
    // SOS Tools
    sosToolsTitle: "SOS Инструменты",
    sosToolsDesc: "Быстрая помощь когда тебе тяжело",
    quickReliefOverwhelmed: "Быстрая помощь когда тебе тяжело",
    breathingExercise478: "Дыхание 4-7-8",
    breathingExerciseDesc: "Успокой нервную систему контролируемым дыханием",
    startBreathing: "Начать дыхание",
    grounding5432: "Заземление 5-4-3-2-1",
    groundingDesc: "Соединись с настоящим моментом",
    beginGrounding: "Начать заземление",
    thoughtRelease: "Освобождение мыслей",
    thoughtReleaseDesc: "Запиши то, что тебя переполняет",
    startWriting: "Начать писать",
    quickMovement: "Быстрое движение",
    quickMovementDesc: "Сними напряжение простыми упражнениями",
    getMoving: "Начать движение",
    stopExercise: "Остановить упражнение",
    breatheIn: "Вдох",
    hold: "Задержка",
    breatheOut: "Выдох",
    fillLungsSlowly: "Медленно и глубоко заполни легкие",
    holdBreathCalm: "Задержи дыхание, оставайся спокойным",
    releaseAllTension: "Отпусти все напряжение и стресс",
    imFeelingBetter: "Мне лучше",
    groundingExerciseTitle: "Упражнение заземления 5-4-3-2-1",
    groundingStep1: "Осмотрись и назови 5 вещей, которые ты видишь",
    groundingStep2: "Заметь 4 вещи, которых ты можешь коснуться или почувствовать",
    groundingStep3: "Прислушайся к 3 разным звукам",
    groundingStep4: "Определи 2 вещи, которые ты можешь почувствовать по запаху",
    groundingStep5: "Подумай об 1 вещи, которую ты можешь попробовать на вкус",
    imMoreGrounded: "Я чувствую себя более заземленным",
    backToTools: "Назад к инструментам",
    crisisHelplineWarning: "Если у тебя есть мысли о самоповреждении, немедленно обратись в службу экстренного реагирования или на горячие линии кризисной помощи.",
    
    // Emergency Contact
    emergencyContactTitle: "Экстренная связь",
    emergencyContactDesc: "Обратись за срочной поддержкой",
    hereToHelpYou: "Мы здесь, чтобы помочь тебе пройти через это",
    crisisWarningMessage: "Если у тебя есть мысли о самоповреждении, пожалуйста, звони в службу экстренного реагирования (112) или на горячие линии кризисной помощи немедленно.",
    tellUsWhatsHappening: "Расскажи нам, что происходит",
    feelingOverwhelmedBecause: "Я чувствую себя подавленным, потому что...",
    howToContactYou: "Как нам с тобой связаться?",
    telegram: "Telegram",
    phone: "Телефон",
    email: "Электронная почта",
    whenNeedResponse: "Когда тебе нужен ответ?",
    within1Hour: "В течение 1 часа",
    within4Hours: "В течение 4 часов",
    within12Hours: "В течение 12 часов",
    sendRequest: "Отправить запрос",
    weGotYourMessage: "Мы получили твое сообщение",
    youreNotAlone: "Ты не один в этом. Кто-то свяжется с тобой в течение",
    inTheMeantime: "А пока попробуй дыхательные упражнения или обратись к проверенному другу.",
    backToMenu: "Назад в меню",
    yourMessageSent: "Твое сообщение отправлено. Помощь уже в пути.",
    pleaseDescribeWhatsHappening: "Пожалуйста, расскажи нам, что происходит",
    
    // Progress
    yourProgressTitle: "Твой прогресс",
    yourProgressDesc: "Отслеживай свой путь исцеления",
    everyStepForwardMatters: "Каждый шаг вперед важен",
    daysOfProgress: "Дней прогресса",
    achievements: "Достижения",
    addProgress: "Добавить прогресс",
    whatProgressMade: "Какой прогресс ты сделал?",
    progressPlaceholder: "Я сделал что-то хорошее для себя...",
    addProgressBtn: "Добавить прогресс",
    cancel: "Отмена",
    yourJourney: "Твой путь",
    youMakingProgress: "Ты делаешь прогресс",
    recoveryNotLinear: "Восстановление не линейно, но каждый шаг важен. Продолжай.",
    progressAddedGreat: "Прогресс добавлен! Отличная работа.",
    pleaseDescribeYourProgress: "Пожалуйста, опиши свой прогресс",
    
    // Примеры записей прогресса
    didntCheckSocialMedia: "Не проверял её соцсети",
    wentToGym: "Ходил в спортзал",
    hadDinnerWithFriends: "Ужинал с друзьями", 
    completedEmotionalCheckup: "Прошел эмоциональную диагностику",
    startedUsingApp: "Начал использовать приложение Верни Себя",
    today: "Сегодня",
    yesterday: "Вчера",
    twoDaysAgo: "2 дня назад",
    threeDaysAgo: "3 дня назад",
    oneWeekAgo: "1 неделю назад",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
