// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbrysbzknwtmxbcxudlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicnlzYnprbnd0bXhiY3h1ZGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzI1NTEsImV4cCI6MjA2NjQ0ODU1MX0.89EWgvUwbLo22m8UAO1ffuPuuf48g3s10Hw1nqdzj0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);